Implement computer choice and enhance player selection
computer choice logic is working with player choice but i cant seem to get the echo text for the "u win" "comp wins" "TIE"

diff --git a/RPS b/RPS
--- a/RPS
+++ b/RPS
@@ -20,8 +20,8 @@ local moves= $rock $paper $scissors
 }
 intro
 player_choice_moves
-1) 
-   rock
+1)
+  rock
    echo "you chose: rock"
    ;;
 2)
@@ -132,6 +132,84 @@ comp_choice_game(){
     comp_choice_game
     
     done
+    }
+    #code structure improv
+comp_choice_game(){
+    RANDNUM=$((RANDOM % 3 + 1))
+    case $RANDNUM in
+    1)
+    echo "comp chose: ROCK"
+    ;;
+    2)
+    echo "comp chose: PAPER"
+    ;;
+    3)
+    echo "comp chose: SCISSORS"
+    ;;
+    *)
+    ;;
+    esac
+    }
+player_choice_move(){
+echo "==CHOOSE UR MOVE=="
+echo "1) ROCK"
+echo "2) PAPER"
+echo "3) SCISSORS"
+read -p "ur move:" choice
+      case $choice in
+    1)
+    echo "you chose: ROCK "
+       ;;
+    2)
+    echo "you chose: PAPER"
+       ;;
+    3)
+    echo "you chose: SCISSORS"
+       ;;
+    *)
+    echo "invalid choice"
+       ;;
+    esac
+    }
+    game_system(){
+    case $RANDNUM in
+    1)
+    {
+    if [[ $player_choice_move -eq 2 ]] then echo "U win"
+    elif [[ $player_choice_move -eq 3 ]] then echo "comp won"
+    elif [[ $player_choice_move -eq 1 ]] then echo "TIE"
+    fi
+    }
+    ;;
+    
+    2)
+    {
+    if [[ $player_choice_move -eq 3 ]] then echo "U win"
+    elif [[ $player_choice_move -eq 1 ]] then echo "comp won"
+    elif [[ $player_choice_move -eq 2 ]] then echo "TIE"
+    fi
+    }
+    ;;
+    
+    3)
+    {
+    if [[ $player_choice_move -eq 2 ]] then echo "U win"
+    elif [[ $player_choice_move -eq 1 ]] then echo "comp won"
+    elif [[ $player_choice_move -eq 3 ]] then echo "TIE"
+    fi
+    }
+    ;;
+    *) 
+    echo "invalid move"
+    ;;
+    esac
+    }
+    {
+    intro
+    player_choice_move
+    comp_choice_game
+    game_system
+    exit 1
     }
 
 
